# Generated by Django 5.0.2 on 2024-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
