# Generated by Django 5.0.7 on 2024-09-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vendors', '0005_vendor_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_ratings', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='vendors.vendor'),
        ),
    ]
