# Generated by Django 5.0.7 on 2024-09-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_rating_owner_alter_rating_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='opened',
            field=models.DateField(blank=True, null=True),
        ),
    ]
