# Generated by Django 5.0.7 on 2024-10-12 11:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendor_social_instegram_vendor_social_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
