# Generated by Django 5.0.7 on 2024-09-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_rename_value_rating_chat_rating_remove_rating_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product_quality_rating',
            new_name='products_quality_rating',
        ),
    ]
