# Generated by Django 5.0.7 on 2024-09-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_rename_product_quality_rating_rating_products_quality_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='handle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
