# Generated by Django 5.0.7 on 2024-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendor_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='social_Instegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='social_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='social_twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='social_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
