# Generated by Django 5.0.7 on 2024-10-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_wishlistitem_wishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], default='Processing', max_length=20),
        ),
    ]
