# Generated by Django 5.0.7 on 2024-10-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_invoice_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='number_of_items',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
