# Generated by Django 5.0.7 on 2024-10-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_invoice_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
