# Generated by Django 5.0.2 on 2024-07-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_review_product_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='INVOICE', max_length=50)),
                ('total', models.IntegerField()),
                ('paid_status', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Processing'), (2, 'Delivered'), (3, 'Shipped'), (4, 'Canceled')])),
                ('products', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
