# Generated by Django 5.0.7 on 2024-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
