# Generated by Django 5.0.7 on 2024-08-31 08:49

import django.db.models.deletion
import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fourth_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='third_image',
        ),
        migrations.AddField(
            model_name='product',
            name='handle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ProductAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.utils.product_attachment_download)),
                ('display', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='products.product')),
            ],
        ),
    ]
