# Generated by Django 5.0.7 on 2024-09-01 11:11

import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productattachment_display_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.utils.product_image_download),
        ),
    ]
